#disabled_rules: # Default Rules에서 비활성화할 규칙
    # 라인 뒤에 공백이 없어야 합니다. https://realm.github.io/SwiftLint/trailing_whitespace.html
#    - trailing_whitespace
    # 강제 캐스팅은 피해야합니다. https://realm.github.io/SwiftLint/force_cast.html
#    - force_cast
    # 강제 언래핑은 피해야합니다. https://realm.github.io/SwiftLint/force_unwrapping.html
#    - force_unwrapping

only_rules:
  - colon
  - fatal_error_message
  - force_cast
  - force_try
  - implicitly_unwrapped_optional
  - legacy_cggeometry_functions
  - legacy_constant
  - legacy_constructor
  - legacy_nsgeometry_functions
  - operator_usage_whitespace
  - redundant_string_enum_value
  - return_arrow_whitespace
  - trailing_newline
  - type_name
  - unused_optional_binding
  - vertical_whitespace
  - void_return
  - custom_rules

colon:
  apply_to_dictionaries: false

indentation: 2

custom_rules:
  no_objcMembers:
    name: "@objcMembers"
    regex: "@objcMembers"
    message: "Explicitly use @objc on each member you want to expose to Objective-C"
    severity: error
  no_direct_standard_out_logs:
    name: "Writing log messages directly to standard out is disallowed"
    regex: "(\\bprint|\\bdebugPrint|\\bdump|Swift\\.print|Swift\\.debugPrint|Swift\\.dump)\\s*\\("
    match_kinds:
    - identifier
    message: "Don't commit `print(…)`, `debugPrint(…)`, or `dump(…)` as they write to standard out in release. Either log to a dedicated logging system or silence this warning in debug-only scenarios explicitly using `// swiftlint:disable:next no_direct_standard_out_logs`"
    severity: warning

excluded: # SwiftLint 검사에서 제외할 파일 경로
  - Carthage
  - Pods
  - ServiceLevelProject/AppDelegate.swift
  - ServiceLevelProject/SceneDelegate.swift
  - ServiceLevelProjectUITests/ServiceLevelProjectUITests.swift
